"""added session tokens

Revision ID: 1c4d8239bc05
Revises: 795da51cf53f
Create Date: 2026-05-07 17:17:41.592065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c4d8239bc05'
down_revision: Union[str, None] = '795da51cf53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
