"""create support tickets table

Revision ID: 588c82b89b97
Revises: c4afe72d86fd
Create Date: 2026-05-12 18:56:47.029669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '588c82b89b97'
down_revision: Union[str, None] = 'c4afe72d86fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
