"""add_token_blacklist_table

Revision ID: 67f7d40191a1
Revises: 626d4ab1492c
Create Date: 2026-05-09 19:30:26.785964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67f7d40191a1'
down_revision: Union[str, None] = '626d4ab1492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
