"""alter_active_sessions_last_seen_at_to_timestamptz

Revision ID: 6a2d8a454e64
Revises: 2cdac93874a4
Create Date: 2026-05-07 17:10:06.204686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6a2d8a454e64'
down_revision: Union[str, None] = '2cdac93874a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
