"""sync schema with models

Revision ID: 7ba4c8acd02e
Revises: 5b25f8695307
Create Date: 2026-05-07 11:16:04.164294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ba4c8acd02e'
down_revision: Union[str, None] = '5b25f8695307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('action_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('active_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ask_mind_messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ask_mind_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ask_mind_suggested_prompts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('ask_mind_suggested_prompts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('integration_channels', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('integration_settings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('integrations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('interview_highlights', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('interview_highlights', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('interview_red_flags', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('interview_red_flags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('interview_skills_to_assess', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('interview_skills_to_assess', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('interview_summaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('interview_transcript_turns', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('interview_transcript_turns', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('meeting_participants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('meeting_participants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('meeting_summaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('password_reset_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scorecard_categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scorecard_categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scorecard_questions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scorecard_questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scorecard_scores', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scorecard_scores', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('scorecard_signals', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scorecard_signals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sso_providers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('summary_decisions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('summary_decisions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('summary_keypoints', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('summary_keypoints', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transcript_segments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('transcript_segments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_meeting_preferences', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_notification_preferences', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_privacy_settings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_security_settings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('waitlist_signups', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workspace_invites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workspace_members', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('workspace_members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspace_members', 'updated_at')
    op.drop_column('workspace_members', 'created_at')
    op.drop_column('workspace_invites', 'updated_at')
    op.drop_column('waitlist_signups', 'updated_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('user_security_settings', 'created_at')
    op.drop_column('user_privacy_settings', 'created_at')
    op.drop_column('user_notification_preferences', 'created_at')
    op.drop_column('user_meeting_preferences', 'created_at')
    op.drop_column('transcript_segments', 'updated_at')
    op.drop_column('transcript_segments', 'created_at')
    op.drop_column('summary_keypoints', 'updated_at')
    op.drop_column('summary_keypoints', 'created_at')
    op.drop_column('summary_decisions', 'updated_at')
    op.drop_column('summary_decisions', 'created_at')
    op.drop_column('sso_providers', 'updated_at')
    op.drop_column('scorecard_signals', 'updated_at')
    op.drop_column('scorecard_signals', 'created_at')
    op.drop_column('scorecard_scores', 'updated_at')
    op.drop_column('scorecard_scores', 'created_at')
    op.drop_column('scorecard_questions', 'updated_at')
    op.drop_column('scorecard_questions', 'created_at')
    op.drop_column('scorecard_categories', 'updated_at')
    op.drop_column('scorecard_categories', 'created_at')
    op.drop_column('password_reset_tokens', 'updated_at')
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meeting_summaries', 'updated_at')
    op.drop_column('meeting_participants', 'updated_at')
    op.drop_column('meeting_participants', 'created_at')
    op.drop_column('interview_transcript_turns', 'updated_at')
    op.drop_column('interview_transcript_turns', 'created_at')
    op.drop_column('interview_summaries', 'updated_at')
    op.drop_column('interview_skills_to_assess', 'updated_at')
    op.drop_column('interview_skills_to_assess', 'created_at')
    op.drop_column('interview_red_flags', 'updated_at')
    op.drop_column('interview_red_flags', 'created_at')
    op.drop_column('interview_highlights', 'updated_at')
    op.drop_column('interview_highlights', 'created_at')
    op.drop_column('integrations', 'updated_at')
    op.drop_column('integration_settings', 'created_at')
    op.drop_column('integration_channels', 'updated_at')
    op.create_index(op.f('ix_email_verification_token_hash'), 'email_verification_tokens', ['token_hash'], unique=False)
    op.drop_column('ask_mind_suggested_prompts', 'updated_at')
    op.drop_column('ask_mind_suggested_prompts', 'created_at')
    op.drop_column('ask_mind_sessions', 'updated_at')
    op.drop_column('ask_mind_messages', 'updated_at')
    op.drop_column('active_sessions', 'updated_at')
    op.drop_column('action_items', 'updated_at')
    op.drop_column('action_items', 'created_at')
    # ### end Alembic commands ###
