"""add unique constraint to refresh_token_hash field

Revision ID: 864df66fbeb7
Revises: a8cbb47717b3
Create Date: 2026-05-06 21:24:10.144305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '864df66fbeb7'
down_revision: Union[str, None] = 'a8cbb47717b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_sessions_refresh_token_hash'), table_name='active_sessions')
    op.create_unique_constraint(None, 'active_sessions', ['refresh_token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'active_sessions', type_='unique')
    op.create_index(op.f('ix_active_sessions_refresh_token_hash'), 'active_sessions', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###
