"""standardize timestamps in database models

Revision ID: 8ba95b973a4a
Revises: 6a2d8a454e64
Create Date: 2026-05-08 19:49:43.277119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8ba95b973a4a'
down_revision: Union[str, None] = '6a2d8a454e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('active_sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_seen_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('active_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('active_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_suggested_prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_suggested_prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integration_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integration_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_highlights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_highlights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_red_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_red_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_scorecards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_scorecards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_skills_to_assess', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_skills_to_assess', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_transcript_turns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_transcript_turns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_transcripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_participants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meetings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # These two refresh_tokens calls are unchanged — no type conversion happening
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_questions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_signals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sso_providers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sso_providers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('summary_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('summary_decisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('summary_keypoints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('summary_keypoints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('transcript_segments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcript_segments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('transcripts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcripts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_interview_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_interview_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_meeting_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_meeting_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_platform_integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_platform_integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_privacy_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_privacy_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_security_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_security_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('waitlist_signups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('waitlist_signups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_invites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspaces', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_members', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_members', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_invites', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('workspace_invites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('waitlist_signups', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('waitlist_signups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_security_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_security_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_privacy_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_privacy_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_platform_integrations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_platform_integrations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notification_preferences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_notification_preferences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_meeting_preferences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_meeting_preferences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_interview_preferences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_interview_preferences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcripts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('transcripts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transcript_segments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('transcript_segments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('summary_keypoints', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('summary_keypoints', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('summary_decisions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('summary_decisions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sso_providers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sso_providers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_signals', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_signals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_scores', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_scores', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_questions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_questions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scorecard_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('scorecard_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('refresh_tokens', 'updated_at')
    op.alter_column('password_reset_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('meetings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meetings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_summaries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_participants', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_participants', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meeting_comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('meeting_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_transcripts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_transcripts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_transcript_turns', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_transcript_turns', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_summaries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('interview_summaries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_skills_to_assess', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_skills_to_assess', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_scorecards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_scorecards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_red_flags', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_red_flags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_highlights', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('interview_highlights', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integrations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integrations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integration_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('integration_channels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('integration_channels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_suggested_prompts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_suggested_prompts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ask_mind_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('ask_mind_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('active_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('active_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('active_sessions', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_seen_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('action_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('action_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
