"""create all tables

Revision ID: cacd5554ba5a
Revises: 
Create Date: 2026-05-05 22:43:03.048268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cacd5554ba5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('active_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_hint', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sso_providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interview_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_interview_type', sa.String(length=120), nullable=True),
    sa.Column('default_duration_min', sa.Integer(), nullable=True),
    sa.Column('evaluation_focus', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_meeting_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unlimited_transcripts', sa.Boolean(), nullable=True),
    sa.Column('join_condition', sa.String(length=40), nullable=True),
    sa.Column('send_recap_to', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interview_goes_live', sa.Boolean(), nullable=True),
    sa.Column('interview_completed', sa.Boolean(), nullable=True),
    sa.Column('weekly_digest', sa.Boolean(), nullable=True),
    sa.Column('product_updates', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platform_integrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform')
    )
    op.create_table('user_privacy_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('require_approval_before_sharing', sa.Boolean(), nullable=True),
    sa.Column('hide_private_manager_notes', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_security_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist_signups',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('candidates',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_initials', sa.String(length=3), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider')
    )
    op.create_table('meetings',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_categories',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_invites',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_table('ask_mind_sessions',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask_mind_suggested_prompts',
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_channels',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ai_tone', sa.String(length=20), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=True),
    sa.Column('questions_total', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviews_interviewer_start', 'interviews', ['interviewer_id', 'scheduled_start'], unique=False)
    op.create_index('ix_interviews_workspace_candidate', 'interviews', ['workspace_id', 'candidate_id'], unique=False)
    op.create_table('meeting_comments',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('speaker_label', sa.String(length=5), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_summaries',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('assignee_name', sa.String(length=120), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['meeting_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ask_mind_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ask_mind_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_settings',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('ai_behavior', sa.String(length=30), nullable=True),
    sa.Column('response_mode', sa.String(length=20), nullable=True),
    sa.Column('show_reason', sa.Boolean(), nullable=True),
    sa.Column('show_confidence', sa.Boolean(), nullable=True),
    sa.Column('tag_ai_responses', sa.Boolean(), nullable=True),
    sa.Column('capture_decisions', sa.Boolean(), nullable=True),
    sa.Column('capture_action_items', sa.Boolean(), nullable=True),
    sa.Column('summary_frequency', sa.String(length=20), nullable=True),
    sa.Column('summary_channel_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['summary_channel_id'], ['integration_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_scorecards',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_summaries',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('custom_question', sa.Text(), nullable=True),
    sa.Column('ai_assessment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_transcripts',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_decisions',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['meeting_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_keypoints',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['meeting_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_participants.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_segments_transcript_seq', 'transcript_segments', ['transcript_id', 'sequence_no'], unique=False)
    op.create_table('interview_highlights',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['interview_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_red_flags',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['interview_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_skills_to_assess',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['interview_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_transcript_turns',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('speaker_name', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('is_ai_question', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['interview_transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_turns_transcript_seq', 'interview_transcript_turns', ['transcript_id', 'sequence_no'], unique=False)
    op.create_table('scorecard_scores',
    sa.Column('scorecard_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('score_pct', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['scorecard_categories.id'], ),
    sa.ForeignKeyConstraint(['scorecard_id'], ['interview_scorecards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_id', 'category_id')
    )
    op.create_table('scorecard_questions',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorecard_signals',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['scorecard_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecard_signals')
    op.drop_table('scorecard_questions')
    op.drop_table('scorecard_scores')
    op.drop_index('ix_interview_turns_transcript_seq', table_name='interview_transcript_turns')
    op.drop_table('interview_transcript_turns')
    op.drop_table('interview_skills_to_assess')
    op.drop_table('interview_red_flags')
    op.drop_table('interview_highlights')
    op.drop_index('ix_transcript_segments_transcript_seq', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_table('summary_keypoints')
    op.drop_table('summary_decisions')
    op.drop_table('interview_transcripts')
    op.drop_table('interview_summaries')
    op.drop_table('interview_scorecards')
    op.drop_table('integration_settings')
    op.drop_table('ask_mind_messages')
    op.drop_table('action_items')
    op.drop_table('transcripts')
    op.drop_table('meeting_summaries')
    op.drop_table('meeting_participants')
    op.drop_table('meeting_comments')
    op.drop_index('ix_interviews_workspace_candidate', table_name='interviews')
    op.drop_index('ix_interviews_interviewer_start', table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('integration_channels')
    op.drop_table('ask_mind_suggested_prompts')
    op.drop_table('ask_mind_sessions')
    op.drop_table('workspace_members')
    op.drop_table('workspace_invites')
    op.drop_table('scorecard_categories')
    op.drop_table('meetings')
    op.drop_table('integrations')
    op.drop_table('candidates')
    op.drop_table('workspaces')
    op.drop_table('waitlist_signups')
    op.drop_table('user_security_settings')
    op.drop_table('user_privacy_settings')
    op.drop_table('user_platform_integrations')
    op.drop_table('user_notification_preferences')
    op.drop_table('user_meeting_preferences')
    op.drop_table('user_interview_preferences')
    op.drop_table('sso_providers')
    op.drop_table('password_reset_tokens')
    op.drop_table('active_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
